# friends routes

GET http://localhost:8080/friends
Content-Type: application/json

####

GET http://localhost:8080/friends/2
Content-Type: application/json

####

POST http://localhost:8080/friends
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann"
}

####
# messages routes

GET http://localhost:8080/messages
Content-Type: application/json

####

GET http://localhost:8080/messages/2
Content-Type: application/json

####

POST http://localhost:8080/messages
Content-Type: application/json

{
  "content": "Max",
  "author": 1
}