GET http://localhost:8080/chats
Content-Type: application/json

###fe

GET http://localhost:8080/chats/2
Content-Type: application/json

###

POST http://localhost:8080/chats
Content-Type: application/json

{
  "name": "chat1"
}